class Language:
    Czech = "cze"
    German = "deu"
    English = "eng"
    Croatian = "hrv"
    Hungarian = "hun"
    Italian = "ita"
    Dutch = "nld"
    Polish = "pol"
    Romanian = "rom"
    Russian = "rus"
    Slovak = "slo"
    Slovene = "slv"
    Spanish = "spa"
    Ukrainian = "ukr"
